#!/bin/bash

# Source this from bash_profile to bootstrap dottle

export DOTTLE_HOME=`dirname $BASH_SOURCE`

function dottle() {
  if [[ -z "$1" ]]; then
    $DOTTLE_HOME/bin/commands/dottle-help dottle
  elif [[ "$1" == "cd" ]]; then
    if [[ -z "$2" ]]; then
      cd $DOTTLE_HOME
    elif [[ -d "$DOTTLE_HOME/topics/$2" ]]; then
      cd "$DOTTLE_HOME/topics/$2"
    else
      echo "No such repository: $2"
    fi
  else
    COMMAND_SCRIPT=$DOTTLE_HOME/bin/commands/dottle-$1
    $COMMAND_SCRIPT ${*:2}
  fi
}
export -f dottle

PLATFORM=`uname | tr [A-Z] [a-z]`
if [[ $PLATFORM == "darwin" ]]; then
  PLATFORM=osx
fi

for topic in $(dottle list using)
do
  export TOPIC_PATH="$DOTTLE_HOME/topics/$topic"
  # Add a topic's bin directory to the path
  if [ -d $TOPIC_PATH/bin ]; then
    export PATH=$TOPIC_PATH/bin:$PATH
  fi
  # Initialize the topic
  if [ -f $TOPIC_PATH/init ]; then
    source $TOPIC_PATH/init
  fi
  # Initialize the topic platform-specific
  if [ -f $TOPIC_PATH/init-$PLATFORM ]; then
    source $TOPIC_PATH/init-$PLATFORM
  fi
done

unset TOPIC_PATH

